<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
 
?>

<?php $testimonial = $block->getCollection();
 //$currencyData= $block->getCurrencyData();
 //print_r($currencyData);
  ?>
<div class="testimonial-data">
<div class="page-title">
</div>
 <div class="col-lef">
 <form class="form contact"
      action="<?php echo $block->getFormAction(); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?php echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
		<legend class="legend"><span><?php echo __('Create New Testimonial') ?></span></legend><br />
        <div class="field name required">
            <label class="label" for="name"><span><?php echo __('First Name') ?></span></label>
            <div class="control">
                <input name="firstname" id="firstname" title="<?php echo __('Frist Name') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field lastname required">
            <label class="label" for="lastname"><span><?php echo __('Last Name') ?></span></label>
            <div class="control">
                <input name="lastname" id="lastname" title="<?php echo __('Last Name') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
         <div class="field email required">
            <label class="label" for="lastname"><span><?php echo __('Email') ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?php echo __('Email') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>

        <div class="field comment required">
            <label class="label" for="comment"><span><?php echo __('Your Testimonial') ?></span></label>
            <div class="control">
                <textarea name="description" id="description" title="<?php echo __('Your Testimonial') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
            </div>
        </div>
        <?php echo $block->getChildHtml('form.additional.info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?php echo __('Submit') ?>" class="action submit primary">
                <span><?php echo __('Save') ?></span>
            </button>
        </div>
    </div>
</form>

 </div>

</div>